#app:
#  datasource:
#    jdbc-url: jdbc:postgresql://localhost:5432/furntrade
#    username: postgres
#    password: 19moniTor97
#    pool-size: 30
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop